In [1]:
from google.colab import files
archivo = files.upload()

Saving iris.data to iris.data


In [2]:
import numpy as np
import tensorflow as tf
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report


In [3]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
iris = pd.read_csv("iris.data",names=names)
#iris.head()
X = iris[["sepal-length","sepal-width","petal-length","petal-width"]]
y = iris[["class"]].values.ravel()

In [20]:

# Codificar las etiquetas (de texto a números)
encoder = LabelEncoder()
labels_encoded = encoder.fit_transform(y)
labels_encoded


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
# Normalizar las características
scaler = StandardScaler()
data_scaled = scaler.fit_transform(X)
data_scaled

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [5]:

# Dividir en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(data_scaled, labels_encoded, test_size=0.2)

# Crear la red neuronal
model = tf.keras.Sequential([

    # 1ra capa: aprender combinaciones no lineales de las 4 variables de entrada.
    tf.keras.layers.Dense(10, activation='relu', input_shape=(4,)),  # Capa oculta con 10 neuronas y capa de entrada implícita de 4 features

    # 2da capa: Reduce la dimensionalidad y combina las representaciones aprendidas por la primera capa.
    tf.keras.layers.Dense(8, activation='relu'),                    # Otra capa oculta

    # softmax convierte los valores en probabilidades que suman 1.
    tf.keras.layers.Dense(3, activation='softmax')                  # Capa de salida con 3 clases
])
# Compilar el modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [7]:
# Entrenar el modelo
history = model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9706 - loss: 0.1928 - val_accuracy: 0.9167 - val_loss: 0.2555
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9510 - loss: 0.2066 - val_accuracy: 0.9167 - val_loss: 0.2516
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9492 - loss: 0.2029 - val_accuracy: 0.9167 - val_loss: 0.2475
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9591 - loss: 0.1923 - val_accuracy: 0.8750 - val_loss: 0.2432
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9506 - loss: 0.1823 - val_accuracy: 0.8750 - val_loss: 0.2396
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9589 - loss: 0.1740 - val_accuracy: 0.9167 - val_loss: 0.2363
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9796 - loss: 0.1612 - val_accuracy: 0.9167 - val_loss: 0.2333
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9445 - loss: 0.1941 - val_accuracy: 0.9167 - val_lo

In [8]:
# Evaluar el modelo en el conjunto de prueba
test_loss, test_accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Accuracy:',test_accuracy)
y_hat = model.predict(X_test)
y_hat


Accuracy: 0.9666666388511658
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 218ms/step


array([[7.9609739e-04, 9.9132490e-01, 7.8788763e-03],
       [3.6937578e-04, 6.6563683e-03, 9.9297428e-01],
       [5.5042233e-02, 6.2875551e-01, 3.1620231e-01],
       [6.6325706e-03, 9.8599839e-01, 7.3690978e-03],
       [5.6325825e-04, 1.2420278e-02, 9.8701644e-01],
       [2.5232616e-03, 3.5535210e-01, 6.4212477e-01],
       [4.6350015e-04, 1.3063503e-02, 9.8647296e-01],
       [5.2437144e-03, 9.1774710e-02, 9.0298164e-01],
       [3.1990188e-04, 7.5827293e-02, 9.2385274e-01],
       [8.9713056e-03, 1.8743876e-01, 8.0359000e-01],
       [7.4892875e-04, 8.1469423e-01, 1.8455678e-01],
       [9.9870938e-01, 1.2405034e-03, 5.0036742e-05],
       [9.0266997e-03, 9.5480990e-01, 3.6163382e-02],
       [3.6015583e-04, 9.8023571e-02, 9.0161628e-01],
       [3.3607954e-04, 4.2849205e-02, 9.5681471e-01],
       [1.2263419e-03, 1.2721662e-01, 8.7155694e-01],
       [9.9856377e-01, 1.4030649e-03, 3.3062839e-05],
       [2.1318700e-03, 9.5746726e-02, 9.0212142e-01],
       [2.1293708e-03, 5.834

In [9]:
y_hat = np.argmax(model.predict(X_test),axis=1)
y_hat

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


array([1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 0, 1, 2, 2, 2, 0, 2, 2, 0, 0, 0,
       2, 2, 1, 1, 1, 1, 1, 0])

In [17]:
# Generar un reporte de clasificación
y_pred = np.argmax(model.predict(X_test), axis=1)
print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred, target_names=encoder.classes_))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

Reporte de clasificación:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.90      1.00      0.95         9
 Iris-virginica       1.00      0.93      0.97        15

       accuracy                           0.97        30
      macro avg       0.97      0.98      0.97        30
   weighted avg       0.97      0.97      0.97        30

